apiVersion: v1
kind: Pod
metadata:
# Choose a unique test pod name
  name: u30                                     
spec:
  containers:
# Choose a unique container name
  - name: u30               
# Path to the Docker image on ECR              
    image: public.ecr.aws/h3v8x5z1/x30:latest                      
    resources:
      limits:
# Number of Alveo U30 cards which should be mounted
        xilinx.com/fpga-xilinx_u30_gen3x4_base_1-0: 1  
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]

